import { createHash } from 'node:crypto';
import { readdirSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

export const root = fileURLToPath(new URL('../../', import.meta.url));
export const migrationDir = path.join(root, 'lib/server/repositories/migrations');
export const snapshotPath = path.join(root, 'supabase-schema.sql');
const literal = (value) => `'${value.replaceAll("'", "''")}'`;

export function readMigrations(directory = migrationDir) {
  const files = readdirSync(directory).filter(name => name.endsWith('.sql')).sort();
  if (!files.length) throw new Error('No database migrations found');
  const versions = new Set();
  return files.map(name => {
    const match = /^(\d{4})_([a-z0-9_]+)\.sql$/.exec(name);
    if (!match || versions.has(match[1])) throw new Error(`Invalid or duplicate migration version: ${name}`);
    versions.add(match[1]);
    const sql = readFileSync(path.join(directory, name), 'utf8');
    return { version: match[1], name, sql, checksum: createHash('sha256').update(sql).digest('hex') };
  });
}

export function renderMigrations(migrations) {
  const knownVersions = migrations.map(m => literal(m.version)).join(', ');
  return `-- Generated by pnpm db:schema. Do not edit; migrations are the source of truth.
-- Works in psql and the database SQL editor. No local roles or cloud credentials included.
BEGIN;
SET LOCAL lock_timeout = '30s';
SET LOCAL search_path = public;
SELECT pg_advisory_xact_lock(824013, 1);
CREATE SCHEMA IF NOT EXISTS studio_migrations;
REVOKE ALL ON SCHEMA studio_migrations FROM PUBLIC;
CREATE TABLE IF NOT EXISTS studio_migrations.versions (
  version TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  checksum TEXT NOT NULL,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
DO $migration_check$ BEGIN
  IF EXISTS (SELECT 1 FROM studio_migrations.versions WHERE version NOT IN (${knownVersions})) THEN
    RAISE EXCEPTION 'Database contains migrations unknown to this checkout; use the current release';
  END IF;
END $migration_check$;
${migrations.map(m => `
DO $migration_${m.version}$ BEGIN
  IF EXISTS (SELECT 1 FROM studio_migrations.versions
    WHERE version = ${literal(m.version)} AND (checksum <> ${literal(m.checksum)} OR name <> ${literal(m.name)})) THEN
    RAISE EXCEPTION 'Applied migration ${m.version} differs from this checkout; restore it and add a new version';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM studio_migrations.versions WHERE version = ${literal(m.version)}) THEN
    IF EXISTS (SELECT 1 FROM studio_migrations.versions WHERE version > ${literal(m.version)}) THEN
      RAISE EXCEPTION 'Migration history has a gap at ${m.version}';
    END IF;
${m.sql.trim().split('\n').map(line => line.trimEnd()).join('\n')}
    INSERT INTO studio_migrations.versions(version, name, checksum)
    VALUES (${literal(m.version)}, ${literal(m.name)}, ${literal(m.checksum)});
    RAISE NOTICE 'Applied migration ${m.name}';
  END IF;
END $migration_${m.version}$;
`).join('')}
NOTIFY pgrst, 'reload schema';
COMMIT;
`;
}
