-- Generated by pnpm db:schema. Do not edit; migrations are the source of truth.
-- Works in psql and the database SQL editor. No local roles or cloud credentials included.
BEGIN;
SET LOCAL lock_timeout = '30s';
SET LOCAL search_path = public;
SELECT pg_advisory_xact_lock(824013, 1);
CREATE SCHEMA IF NOT EXISTS studio_migrations;
REVOKE ALL ON SCHEMA studio_migrations FROM PUBLIC;
CREATE TABLE IF NOT EXISTS studio_migrations.versions (
  version TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  checksum TEXT NOT NULL,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
DO $migration_check$ BEGIN
  IF EXISTS (SELECT 1 FROM studio_migrations.versions WHERE version NOT IN ('0001', '0002', '0003')) THEN
    RAISE EXCEPTION 'Database contains migrations unknown to this checkout; use the current release';
  END IF;
END $migration_check$;

DO $migration_0001$ BEGIN
  IF EXISTS (SELECT 1 FROM studio_migrations.versions
    WHERE version = '0001' AND (checksum <> '2a6c4827c05da7101e4a5a226f19be9ab1e2951226ad47da16e7c83093397d7d' OR name <> '0001_baseline.sql')) THEN
    RAISE EXCEPTION 'Applied migration 0001 differs from this checkout; restore it and add a new version';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM studio_migrations.versions WHERE version = '0001') THEN
    IF EXISTS (SELECT 1 FROM studio_migrations.versions WHERE version > '0001') THEN
      RAISE EXCEPTION 'Migration history has a gap at 0001';
    END IF;
-- Refuse historical layouts that require a separate reviewed data migration.
DO $$ BEGIN
  IF to_regclass('public.playground_shortcuts') IS NOT NULL THEN
    RAISE EXCEPTION 'Legacy playground_shortcuts exists; review its data migration before adopting the baseline';
  END IF;
  IF to_regclass('public.infinite_canvas_projects') IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns WHERE table_schema = 'public'
      AND table_name = 'infinite_canvas_projects' AND column_name = 'project_id'
  ) THEN
    RAISE EXCEPTION 'Legacy Canvas layout detected; review the Canvas v2 data migration first';
  END IF;
END $$;
CREATE TEMP TABLE studio_migration_existing ON COMMIT DROP AS
  SELECT tablename AS name FROM pg_tables WHERE schemaname = 'public';

-- Lemon8 AI Studio 数据库表结构
-- Initial supported baseline; applied once by the versioned migration runner.

-- 1. 用户表
CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid(),
  display_name VARCHAR(255),
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 图片资源表
CREATE TABLE IF NOT EXISTS image_assets (
  id VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid(),
  url TEXT NOT NULL,
  dir VARCHAR(255) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  region VARCHAR(64) NOT NULL,
  type VARCHAR(32) NOT NULL, -- generation, reference, dataset, upload
  project_id VARCHAR(36),
  generation_id VARCHAR(36),
  meta JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS image_assets_type_idx ON image_assets(type);
CREATE INDEX IF NOT EXISTS image_assets_project_id_idx ON image_assets(project_id);
CREATE INDEX IF NOT EXISTS image_assets_generation_id_idx ON image_assets(generation_id);

-- 3. 生成记录表
CREATE TABLE IF NOT EXISTS generations (
  id VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid(),
  status VARCHAR(32) DEFAULT 'pending', -- pending, completed, failed
  progress INTEGER,
  progress_stage VARCHAR(64),
  user_id VARCHAR(36),
  project_id VARCHAR(36),
  llm_response TEXT,
  output_image_id VARCHAR(36),
  source_image_id VARCHAR(36),
  output_url TEXT,
  config JSONB,
  -- 交互统计字段
  like_count INTEGER DEFAULT 0,
  moodboard_add_count INTEGER DEFAULT 0,
  download_count INTEGER DEFAULT 0,
  edit_count INTEGER DEFAULT 0,
  last_liked_at TIMESTAMPTZ,
  last_moodboard_added_at TIMESTAMPTZ,
  last_downloaded_at TIMESTAMPTZ,
  last_edited_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS generations_user_id_idx ON generations(user_id);
CREATE INDEX IF NOT EXISTS generations_project_id_idx ON generations(project_id);
CREATE INDEX IF NOT EXISTS generations_created_at_idx ON generations(created_at DESC);
CREATE INDEX IF NOT EXISTS generations_status_idx ON generations(status);
-- 交互统计索引（用于排序筛选）
CREATE INDEX IF NOT EXISTS generations_download_count_idx ON generations(download_count DESC);
CREATE INDEX IF NOT EXISTS generations_like_count_idx ON generations(like_count DESC);
CREATE INDEX IF NOT EXISTS generations_last_downloaded_at_idx ON generations(last_downloaded_at DESC);

-- 3.1 生成记录点赞表（去重）
CREATE TABLE IF NOT EXISTS generation_likes (
  id VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid(),
  generation_id VARCHAR(36) NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(generation_id, user_id)
);

CREATE INDEX IF NOT EXISTS generation_likes_generation_id_idx ON generation_likes(generation_id);
CREATE INDEX IF NOT EXISTS generation_likes_user_id_idx ON generation_likes(user_id);

-- 4. 预设表
CREATE TABLE IF NOT EXISTS presets (
  id VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  cover_url TEXT,
  cover_data TEXT,
  config JSONB,
  edit_config JSONB,
  category VARCHAR(64),
  project_id VARCHAR(36),
  type VARCHAR(32), -- generation, edit
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS presets_category_idx ON presets(category);
CREATE INDEX IF NOT EXISTS presets_type_idx ON presets(type);

-- 5. 预设分类表
CREATE TABLE IF NOT EXISTS preset_categories (
  id SERIAL PRIMARY KEY,
  key VARCHAR(64) NOT NULL UNIQUE,
  categories JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. 风格堆栈表
CREATE TABLE IF NOT EXISTS style_stacks (
  id VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  prompt TEXT NOT NULL,
  image_paths JSONB DEFAULT '[]',
  preview_urls JSONB DEFAULT '[]',
  collage_image_url TEXT,
  collage_config JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6.1 Moodboard Card 表

CREATE TABLE IF NOT EXISTS moodboard_cards (
  id VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid(),
  code VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  sort_order INTEGER,
  is_enabled BOOLEAN DEFAULT true,
  cover_title TEXT,
  cover_subtitle TEXT,
  cover_storage_key TEXT,
  cover_url TEXT,
  model_id VARCHAR(255),
  default_aspect_ratio VARCHAR(32),
  default_width INTEGER,
  default_height INTEGER,
  allow_model_change BOOLEAN DEFAULT true,
  prompt_template TEXT,
  prompt_fields JSONB DEFAULT '[]',
  prompt_config JSONB,
  moodboard_description TEXT,
  example_prompts JSONB DEFAULT '[]',
  gallery_order JSONB DEFAULT '[]',
  creator VARCHAR(255),
  publish_status VARCHAR(32) DEFAULT 'draft',
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS moodboard_cards_sort_order_idx ON moodboard_cards(sort_order ASC);
CREATE INDEX IF NOT EXISTS moodboard_cards_created_at_idx ON moodboard_cards(created_at ASC);

-- 7. 工具预设表
CREATE TABLE IF NOT EXISTS tool_presets (
  id VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid(),
  tool_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  values JSONB,
  thumbnail TEXT,
  timestamp BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS tool_presets_tool_id_idx ON tool_presets(tool_id);

-- 修复已存在的表：将 timestamp 从 INTEGER 改为 BIGINT
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'tool_presets'
    AND column_name = 'timestamp'
    AND data_type = 'integer'
  ) THEN
    ALTER TABLE tool_presets ALTER COLUMN timestamp TYPE BIGINT;
  END IF;
END $$;

-- 8. 数据集条目表
CREATE TABLE IF NOT EXISTS dataset_entries (
  id VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid(),
  collection_name VARCHAR(255) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  url TEXT NOT NULL,
  prompt TEXT,
  width INTEGER,
  height INTEGER,
  format VARCHAR(32),
  size INTEGER,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS dataset_entries_collection_name_idx ON dataset_entries(collection_name);

-- 9. 数据集集合表
CREATE TABLE IF NOT EXISTS dataset_collections (
  id VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. 无限画布项目表
CREATE TABLE IF NOT EXISTS infinite_canvas_projects (
  id VARCHAR(36) PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id VARCHAR(36) NOT NULL,
  user_id VARCHAR(36),
  project_name VARCHAR(255) NOT NULL,
  cover_url TEXT,
  node_count INTEGER NOT NULL DEFAULT 0,
  canvas_viewport JSONB NOT NULL DEFAULT '{"x": 0, "y": 0, "scale": 1}'::jsonb,
  last_opened_panel VARCHAR(32),
  nodes JSONB NOT NULL DEFAULT '[]'::jsonb,
  edges JSONB NOT NULL DEFAULT '[]'::jsonb,
  assets JSONB NOT NULL DEFAULT '[]'::jsonb,
  history JSONB NOT NULL DEFAULT '[]'::jsonb,
  run_queue JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS infinite_canvas_projects_project_id_uidx ON infinite_canvas_projects(project_id);
CREATE INDEX IF NOT EXISTS infinite_canvas_projects_user_id_idx ON infinite_canvas_projects(user_id);
CREATE INDEX IF NOT EXISTS infinite_canvas_projects_updated_at_idx ON infinite_canvas_projects(updated_at DESC);

-- 11. 启用 Row Level Security (RLS)
-- 注意：根据你的安全需求配置 RLS 策略
-- 以下是最基本的允许所有操作的策略（生产环境请根据需要调整）

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'users') THEN
    ALTER TABLE users ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'image_assets') THEN
    ALTER TABLE image_assets ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'generations') THEN
    ALTER TABLE generations ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'generation_likes') THEN
    ALTER TABLE generation_likes ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'presets') THEN
    ALTER TABLE presets ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'preset_categories') THEN
    ALTER TABLE preset_categories ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'style_stacks') THEN
    ALTER TABLE style_stacks ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'moodboard_cards') THEN
    ALTER TABLE moodboard_cards ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'tool_presets') THEN
    ALTER TABLE tool_presets ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'dataset_entries') THEN
    ALTER TABLE dataset_entries ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'dataset_collections') THEN
    ALTER TABLE dataset_collections ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'infinite_canvas_projects') THEN
    ALTER TABLE infinite_canvas_projects ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;

-- 允许匿名访问（根据需要调整）
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'users') THEN
    CREATE POLICY "Allow anonymous access" ON users FOR ALL USING (true);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'image_assets') THEN
    CREATE POLICY "Allow anonymous access" ON image_assets FOR ALL USING (true);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'generations') THEN
    CREATE POLICY "Allow anonymous access" ON generations FOR ALL USING (true);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'generation_likes') THEN
    CREATE POLICY "Allow anonymous access" ON generation_likes FOR ALL USING (true);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'presets') THEN
    CREATE POLICY "Allow anonymous access" ON presets FOR ALL USING (true);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'preset_categories') THEN
    CREATE POLICY "Allow anonymous access" ON preset_categories FOR ALL USING (true);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'style_stacks') THEN
    CREATE POLICY "Allow anonymous access" ON style_stacks FOR ALL USING (true);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'moodboard_cards') THEN
    CREATE POLICY "Allow anonymous access" ON moodboard_cards FOR ALL USING (true);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'tool_presets') THEN
    CREATE POLICY "Allow anonymous access" ON tool_presets FOR ALL USING (true);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'dataset_entries') THEN
    CREATE POLICY "Allow anonymous access" ON dataset_entries FOR ALL USING (true);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'dataset_collections') THEN
    CREATE POLICY "Allow anonymous access" ON dataset_collections FOR ALL USING (true);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM studio_migration_existing WHERE name = 'infinite_canvas_projects') THEN
    CREATE POLICY "Allow anonymous access" ON infinite_canvas_projects FOR ALL USING (true);
  END IF;
END $$;

-- 完成
-- 执行完成后，你的 Supabase 数据库就准备就绪了！
    INSERT INTO studio_migrations.versions(version, name, checksum)
    VALUES ('0001', '0001_baseline.sql', '2a6c4827c05da7101e4a5a226f19be9ab1e2951226ad47da16e7c83093397d7d');
    RAISE NOTICE 'Applied migration 0001_baseline.sql';
  END IF;
END $migration_0001$;

DO $migration_0002$ BEGIN
  IF EXISTS (SELECT 1 FROM studio_migrations.versions
    WHERE version = '0002' AND (checksum <> '85a81857f3d0378080beeec21b149a737e01652ce849982c1a430b4d1fbf4293' OR name <> '0002_business_fields_and_stats.sql')) THEN
    RAISE EXCEPTION 'Applied migration 0002 differs from this checkout; restore it and add a new version';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM studio_migrations.versions WHERE version = '0002') THEN
    IF EXISTS (SELECT 1 FROM studio_migrations.versions WHERE version > '0002') THEN
      RAISE EXCEPTION 'Migration history has a gap at 0002';
    END IF;
-- Business fields and statistics shared by local and deployed environments.
ALTER TABLE preset_categories ALTER COLUMN key SET DEFAULT 'default';
ALTER TABLE users ADD COLUMN IF NOT EXISTS password TEXT;
ALTER TABLE image_assets ADD COLUMN IF NOT EXISTS storage_key TEXT;
ALTER TABLE dataset_entries ADD COLUMN IF NOT EXISTS prompt_zh TEXT;
ALTER TABLE dataset_entries ADD COLUMN IF NOT EXISTS prompt_en TEXT;
ALTER TABLE dataset_entries ADD COLUMN IF NOT EXISTS order_idx INTEGER DEFAULT 0;
ALTER TABLE dataset_collections ADD COLUMN IF NOT EXISTS order_arr JSONB DEFAULT '[]';
ALTER TABLE dataset_collections ADD COLUMN IF NOT EXISTS system_prompt TEXT;
CREATE TABLE IF NOT EXISTS site_stats (
  key TEXT PRIMARY KEY,
  count BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE OR REPLACE FUNCTION increment_site_stat(p_key TEXT, p_delta INTEGER DEFAULT 1)
RETURNS VOID LANGUAGE sql AS $$
  INSERT INTO site_stats(key, count) VALUES(p_key, p_delta)
  ON CONFLICT(key) DO UPDATE SET count = site_stats.count + EXCLUDED.count, updated_at = NOW();
$$;
DROP FUNCTION IF EXISTS increment_like_count(TEXT);
CREATE OR REPLACE FUNCTION increment_like_count(p_generation_id TEXT, p_now TIMESTAMPTZ)
RETURNS VOID LANGUAGE sql AS $$
  UPDATE generations SET like_count = COALESCE(like_count, 0) + 1, last_liked_at = p_now
  WHERE id = p_generation_id;
$$;
    INSERT INTO studio_migrations.versions(version, name, checksum)
    VALUES ('0002', '0002_business_fields_and_stats.sql', '85a81857f3d0378080beeec21b149a737e01652ce849982c1a430b4d1fbf4293');
    RAISE NOTICE 'Applied migration 0002_business_fields_and_stats.sql';
  END IF;
END $migration_0002$;

DO $migration_0003$ BEGIN
  IF EXISTS (SELECT 1 FROM studio_migrations.versions
    WHERE version = '0003' AND (checksum <> '63a006c028c921d4ec1d84b34aab342b8cdc9fd3e7014bcb8c25e52601c9aea3' OR name <> '0003_history_config_cas.sql')) THEN
    RAISE EXCEPTION 'Applied migration 0003 differs from this checkout; restore it and add a new version';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM studio_migrations.versions WHERE version = '0003') THEN
    IF EXISTS (SELECT 1 FROM studio_migrations.versions WHERE version > '0003') THEN
      RAISE EXCEPTION 'Migration history has a gap at 0003';
    END IF;
-- Compare-and-swap uses a POST body so configs containing data URLs do not exceed URL limits.
CREATE OR REPLACE FUNCTION update_owned_history_config(
  p_id TEXT,
  p_owner_id TEXT,
  p_expected_config JSONB,
  p_config JSONB
)
RETURNS TABLE(id VARCHAR)
LANGUAGE sql
SECURITY INVOKER
SET search_path = public
AS $$
  UPDATE public.generations AS g
  SET config = p_config
  WHERE g.id = p_id AND g.user_id = p_owner_id AND g.config = p_expected_config
  RETURNING g.id;
$$;
NOTIFY pgrst, 'reload schema';
    INSERT INTO studio_migrations.versions(version, name, checksum)
    VALUES ('0003', '0003_history_config_cas.sql', '63a006c028c921d4ec1d84b34aab342b8cdc9fd3e7014bcb8c25e52601c9aea3');
    RAISE NOTICE 'Applied migration 0003_history_config_cas.sql';
  END IF;
END $migration_0003$;

NOTIFY pgrst, 'reload schema';
COMMIT;
