import { useCallback, useState } from "react";
import { SETTINGS_STORAGE_KEY } from "@/lib/constants";
import { getApiBase } from "@/lib/api-base";
import { buildFluxKleinWorkflow } from "@/lib/api/fluxklein-workflow";
import { runDirectComfyWorkflow } from "@/lib/comfyui/browser-client";
import { getConfiguredDirectComfyUrl, shouldUseDirectComfyUi } from "@/lib/comfyui/direct-config";

export interface IUsePostFluxKlein {
  prompt: string;
  width: number;
  height: number;
  seed?: number;
  batchSize?: number;
  referenceImages?: string[];
  onSuccess: (outputs: Blob[]) => void;
  onError: (error: unknown) => void;
}

export const usePostFluxKlein = () => {
  const [loading, setLoading] = useState(false);

  const doPost = useCallback(async ({ prompt, width, height, seed, batchSize, referenceImages, onSuccess, onError }: IUsePostFluxKlein) => {
    setLoading(true);
    const nowMs = typeof performance !== "undefined" && typeof performance.now === "function"
      ? () => performance.now()
      : () => Date.now();
    const requestId = typeof crypto !== "undefined" && typeof crypto.randomUUID === "function"
      ? crypto.randomUUID()
      : `${Date.now()}-${Math.random().toString(16).slice(2)}`;
    const startAt = nowMs();
    try {
      let apiKey: string | undefined;

      try {
        const storedSettings = localStorage.getItem(SETTINGS_STORAGE_KEY);
        if (storedSettings) {
          const settings = JSON.parse(storedSettings);
          if (settings.apiKey) apiKey = settings.apiKey;
        }
      } catch (e) {
        console.error("Failed to load settings", e);
      }

      const apiBase = getApiBase();
      const directComfyUrl = getConfiguredDirectComfyUrl();

      if (shouldUseDirectComfyUi(directComfyUrl)) {
        const { workflow, viewComfyInputs } = await buildFluxKleinWorkflow({
          prompt,
          width,
          height,
          seed,
          batchSize,
          referenceImages,
        });
        console.info("[FluxKlein][Front] request_start", {
          requestId,
          mode: "browser-direct",
          comfyUrl: directComfyUrl,
        });
        const blobs = await runDirectComfyWorkflow({
          workflow,
          viewComfy: {
            inputs: viewComfyInputs,
            textOutputEnabled: false,
          },
          apiKey,
          comfyUrl: directComfyUrl,
          requestId,
        });
        console.info("[FluxKlein][Front] stream_done", {
          requestId,
          outputs: blobs.length,
          elapsedMs: Math.round(nowMs() - startAt),
          mode: "browser-direct",
        });
        if (blobs.length > 0) {
          onSuccess(blobs);
          return;
        }
        throw new Error("No images were generated by the workflow.");
      }

      console.info("[FluxKlein][Front] request_start", { requestId, apiBase, comfyUrlSource: "server-env-COMFYUI_API_URL", mode: "server-proxy" });
      const response = await fetch(`${apiBase}/comfy-fluxklein`, {
        method: "POST",
        headers: { "Content-Type": "application/json", "x-request-id": requestId },
        body: JSON.stringify({
          prompt,
          width,
          height,
          seed,
          batchSize,
          referenceImages,
          apiKey,
        }),
      });
      const responseAt = nowMs();
      console.info("[FluxKlein][Front] response_headers", {
        requestId,
        status: response.status,
        elapsedMs: Math.round(responseAt - startAt),
      });

      if (!response.ok) {
        const rawText = await response.text().catch(() => "");
        let responseError: unknown = {};
        if (rawText) {
          try {
            responseError = JSON.parse(rawText);
          } catch {
            responseError = { message: rawText };
          }
        }
        const errorMessage = extractFluxKleinErrorMessage(responseError) || `HTTP ${response.status}`;
        const wrappedError = new Error(errorMessage);
        (wrappedError as Error & { details?: unknown; status?: number }).details = responseError;
        (wrappedError as Error & { details?: unknown; status?: number }).status = response.status;
        throw wrappedError;
      }

      if (!response.body) throw new Error("No response body");

      const reader = response.body.getReader();
      let buffer: Uint8Array = new Uint8Array(0);
      const output: Blob[] = [];
      const separator = new TextEncoder().encode("--BLOB_SEPARATOR--");

      let firstChunkAt: number | null = null;
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        if (firstChunkAt === null) {
          firstChunkAt = nowMs();
          console.info("[FluxKlein][Front] first_chunk", {
            requestId,
            elapsedMs: Math.round(firstChunkAt - startAt),
          });
        }
        buffer = concatUint8Arrays(buffer, value);
        let separatorIndex: number;
        while ((separatorIndex = findSubarray(buffer, separator)) !== -1) {
          const outputPart = buffer.slice(0, separatorIndex);
          buffer = buffer.slice(separatorIndex + separator.length);
          const mimeEndIndex = findSubarray(outputPart, new TextEncoder().encode("\r\n\r\n"));
          if (mimeEndIndex !== -1) {
            const mimeHeader = new TextDecoder().decode(outputPart.slice(0, mimeEndIndex));
            const mimeType = mimeHeader.split(": ")[1]?.trim() || "application/octet-stream";
            const outputData = outputPart.slice(mimeEndIndex + 4);
            output.push(new Blob([outputData], { type: mimeType }));
          }
        }
      }

      const doneAt = nowMs();
      console.info("[FluxKlein][Front] stream_done", {
        requestId,
        outputs: output.length,
        elapsedMs: Math.round(doneAt - startAt),
      });
      if (output.length > 0) onSuccess(output);
      else throw new Error("No images were generated by the workflow.");
    } catch (error) {
      const errorAt = nowMs();
      const errorMessage = extractFluxKleinErrorMessage(error);
      console.error("[FluxKlein][Front] request_error", {
        requestId,
        elapsedMs: Math.round(errorAt - startAt),
        error,
        errorMessage,
      });
      if (error instanceof Error) {
        onError(error);
      } else {
        onError(new Error(errorMessage || "FluxKlein request failed"));
      }
    } finally {
      setLoading(false);
    }
  }, []);

  return { doPost, loading };
};

function concatUint8Arrays(a: Uint8Array, b: Uint8Array): Uint8Array {
  const c = new Uint8Array(a.length + b.length);
  c.set(a);
  c.set(b, a.length);
  return c;
}

function findSubarray(arr: Uint8Array, separator: Uint8Array): number {
  outer: for (let i = 0; i <= arr.length - separator.length; i++) {
    for (let j = 0; j < separator.length; j++) {
      if (arr[i + j] !== separator[j]) continue outer;
    }
    return i;
  }
  return -1;
}

function extractFluxKleinErrorMessage(error: unknown): string {
  if (error instanceof Error && error.message) return error.message;
  if (typeof error === "string") return error;
  if (!error || typeof error !== "object") return "FluxKlein request failed";

  const obj = error as Record<string, unknown>;
  const details = obj.details as Record<string, unknown> | undefined;
  const topLevelError = typeof obj.error === "string" ? obj.error : undefined;
  const topLevelMessage = typeof obj.message === "string" ? obj.message : undefined;
  const topLevelErrorMsg = typeof obj.errorMsg === "string" ? obj.errorMsg : undefined;
  const detailErrorMsg = details && typeof details.errorMsg === "string" ? details.errorMsg : undefined;
  const detailErrorDetails = details?.errorDetails;

  let detailString = "";
  if (Array.isArray(detailErrorDetails)) {
    detailString = detailErrorDetails.map((item) => String(item)).filter(Boolean).join("; ");
  } else if (typeof detailErrorDetails === "string") {
    detailString = detailErrorDetails;
  }

  const base = topLevelError || topLevelMessage || topLevelErrorMsg || detailErrorMsg || "";
  if (base && detailString && !base.includes(detailString)) {
    return `${base}: ${detailString}`;
  }
  if (base) return base;
  if (detailString) return detailString;

  try {
    return JSON.stringify(error);
  } catch {
    return "FluxKlein request failed";
  }
}
