import { useCallback, useState } from "react";
import { SETTINGS_STORAGE_KEY } from "@/lib/constants";
import { getApiBase } from "@/lib/api-base";

export interface IUsePostFluxKlein {
  prompt: string;
  width: number;
  height: number;
  seed?: number;
  batchSize?: number;
  referenceImages?: string[];
  onSuccess: (outputs: Blob[]) => void;
  onError: (error: unknown) => void;
}

export const usePostFluxKlein = () => {
  const [loading, setLoading] = useState(false);

  const doPost = useCallback(async ({ prompt, width, height, seed, batchSize, referenceImages, onSuccess, onError }: IUsePostFluxKlein) => {
    setLoading(true);
    try {
      let apiKey: string | undefined;
      let comfyUrl: string | undefined;

      try {
        const storedSettings = localStorage.getItem(SETTINGS_STORAGE_KEY);
        if (storedSettings) {
          const settings = JSON.parse(storedSettings);
          if (settings.apiKey) apiKey = settings.apiKey;
          if (settings.comfyUrl) comfyUrl = settings.comfyUrl;
        }
      } catch (e) {
        console.error("Failed to load settings", e);
      }

      const response = await fetch(`${getApiBase()}/comfy-fluxklein`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prompt,
          width,
          height,
          seed,
          batchSize,
          referenceImages,
          apiKey,
          comfyUrl,
        }),
      });

      if (!response.ok) {
        const responseError = await response.json().catch(() => ({}));
        throw responseError;
      }

      if (!response.body) throw new Error("No response body");

      const reader = response.body.getReader();
      let buffer: Uint8Array = new Uint8Array(0);
      const output: Blob[] = [];
      const separator = new TextEncoder().encode("--BLOB_SEPARATOR--");

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer = concatUint8Arrays(buffer, value);
        let separatorIndex: number;
        while ((separatorIndex = findSubarray(buffer, separator)) !== -1) {
          const outputPart = buffer.slice(0, separatorIndex);
          buffer = buffer.slice(separatorIndex + separator.length);
          const mimeEndIndex = findSubarray(outputPart, new TextEncoder().encode("\r\n\r\n"));
          if (mimeEndIndex !== -1) {
            const mimeHeader = new TextDecoder().decode(outputPart.slice(0, mimeEndIndex));
            const mimeType = mimeHeader.split(": ")[1]?.trim() || "application/octet-stream";
            const outputData = outputPart.slice(mimeEndIndex + 4);
            output.push(new Blob([outputData], { type: mimeType }));
          }
        }
      }

      if (output.length > 0) onSuccess(output);
      else throw new Error("No images were generated by the workflow.");
    } catch (error) {
      onError(error);
    } finally {
      setLoading(false);
    }
  }, []);

  return { doPost, loading };
};

function concatUint8Arrays(a: Uint8Array, b: Uint8Array): Uint8Array {
  const c = new Uint8Array(a.length + b.length);
  c.set(a);
  c.set(b, a.length);
  return c;
}

function findSubarray(arr: Uint8Array, separator: Uint8Array): number {
  outer: for (let i = 0; i <= arr.length - separator.length; i++) {
    for (let j = 0; j < separator.length; j++) {
      if (arr[i + j] !== separator[j]) continue outer;
    }
    return i;
  }
  return -1;
}
